[2018-04-23 22:53:44,073] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_float:58 , 是测试点"MyCacl"下的用例"整数加小数",返回的结果res=3.8]
[2018-04-23 22:53:44,079] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:52 , 是测试点"MyCacl"下的用例"整数加整数",返回的结果res=2]
[2018-04-23 22:53:44,083] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_negativeNumber:64 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=-4]
[2018-04-23 22:54:00,946] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_float:58 , 是测试点"MyCacl"下的用例"整数加小数",返回的结果res=3.8]
[2018-04-23 22:54:00,950] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:52 , 是测试点"MyCacl"下的用例"整数加整数",返回的结果res=2]
[2018-04-23 22:54:00,954] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_negativeNumber:64 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=-4]
[2018-04-23 22:58:27,637] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_float:58 , 是测试点"MyCacl"下的用例"整数加小数",返回的结果res=3.8]
[2018-04-23 22:58:27,641] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:52 , 是测试点"MyCacl"下的用例"整数加整数",返回的结果res=2]
[2018-04-23 22:58:27,645] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_negativeNumber:64 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=-4]
[2018-04-23 23:03:17,016] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:52 , 是测试点"MyCacl"下的用例"整数加整数",返回的结果res=2]
[2018-04-23 23:03:17,019] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_float:58 , 是测试点"MyCacl"下的用例"整数加小数",返回的结果res=3.8]
[2018-04-23 23:03:17,022] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_negativeNumber:64 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=-4]
[2018-04-23 23:09:18,933] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_all:30 , 是测试点"SelectMock"下的用例"查询所有",返回的结果res=连接错误。]
[2018-04-23 23:10:10,754] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_all:30 , 是测试点"SelectMock"下的用例"查询所有",返回的结果res=连接错误。]
[2018-04-23 23:10:11,762] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_first:42 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:10:12,773] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_last:54 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:10:13,780] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_notExist:66 , 是测试点"SelectMock"下的用例"查询一个不存在的",返回的结果res=连接错误。]
[2018-04-23 23:12:25,588] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:52 , 是测试点"MyCacl"下的用例"整数加整数",返回的结果res=2]
[2018-04-23 23:12:25,592] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_float:58 , 是测试点"MyCacl"下的用例"整数加小数",返回的结果res=3.8]
[2018-04-23 23:12:25,596] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_negativeNumber:64 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=-4]
[2018-04-23 23:12:44,907] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:52 , 是测试点"MyCacl"下的用例"整数加整数",返回的结果res=2]
[2018-04-23 23:12:44,910] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_float:58 , 是测试点"MyCacl"下的用例"整数加小数",返回的结果res=3.8]
[2018-04-23 23:12:44,913] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_negativeNumber:64 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=-4]
[2018-04-23 23:13:22,161] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:52 , 是测试点"MyCacl"下的用例"整数加整数",返回的结果res=2]
[2018-04-23 23:13:22,164] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_float:58 , 是测试点"MyCacl"下的用例"整数加小数",返回的结果res=3.8]
[2018-04-23 23:13:22,167] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_negativeNumber:64 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=-4]
[2018-04-23 23:13:22,170] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_letter:73 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=类型错误]
[2018-04-23 23:13:54,936] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_all:30 , 是测试点"SelectMock"下的用例"查询所有",返回的结果res=连接错误。]
[2018-04-23 23:13:55,944] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_first:42 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:13:56,951] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_last:54 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:13:57,957] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_notExist:66 , 是测试点"SelectMock"下的用例"查询一个不存在的",返回的结果res=连接错误。]
[2018-04-23 23:14:31,626] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_float:58 , 是测试点"MyCacl"下的用例"整数加小数",返回的结果res=3.8]
[2018-04-23 23:14:31,630] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:52 , 是测试点"MyCacl"下的用例"整数加整数",返回的结果res=2]
[2018-04-23 23:14:31,634] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_letter:73 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=类型错误]
[2018-04-23 23:14:31,638] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_negativeNumber:64 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=-4]
[2018-04-23 23:14:32,652] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_all:30 , 是测试点"SelectMock"下的用例"查询所有",返回的结果res=连接错误。]
[2018-04-23 23:14:33,662] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_first:42 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:14:34,675] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_last:54 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:14:35,686] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_notExist:66 , 是测试点"SelectMock"下的用例"查询一个不存在的",返回的结果res=连接错误。]
[2018-04-23 23:19:20,977] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_first:43 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:19:21,986] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_last:55 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:19:22,988] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_notExist:67 , 是测试点"SelectMock"下的用例"查询一个不存在的",返回的结果res=连接错误。]
[2018-04-23 23:20:35,184] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_all:31 , 是测试点"SelectMock"下的用例"查询所有",返回的结果res=连接错误。]
[2018-04-23 23:20:36,190] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_first:43 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:20:37,195] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_last:55 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:20:38,221] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_notExist:67 , 是测试点"SelectMock"下的用例"查询一个不存在的",返回的结果res=连接错误。]
[2018-04-23 23:21:43,274] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_all:30 , 是测试点"SelectMock"下的用例"查询所有",返回的结果res=连接错误。]
[2018-04-23 23:21:44,282] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_first:42 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:21:45,295] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_last:54 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:21:46,304] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_notExist:66 , 是测试点"SelectMock"下的用例"查询一个不存在的",返回的结果res=连接错误。]
[2018-04-23 23:22:21,758] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:53 , 是测试点"MyCacl"下的用例"整数加整数",返回的结果res=2]
[2018-04-23 23:22:21,761] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_float:59 , 是测试点"MyCacl"下的用例"整数加小数",返回的结果res=3.8]
[2018-04-23 23:22:21,763] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_negativeNumber:65 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=-4]
[2018-04-23 23:22:21,766] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_letter:74 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=类型错误]
[2018-04-23 23:23:22,450] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:53 , 是测试点"MyCacl"下的用例"整数加整数",返回的结果res=2]
[2018-04-23 23:23:22,452] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_float:59 , 是测试点"MyCacl"下的用例"整数加小数",返回的结果res=3.8]
[2018-04-23 23:23:22,454] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_negativeNumber:65 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=-4]
[2018-04-23 23:23:22,458] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_letter:74 , 是测试点"MyCacl"下的用例"整数加字母",返回的结果res=类型错误]
[2018-04-23 23:24:12,793] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:54 , 是测试点"MyCacl"下的用例"整数加整数",返回的结果res=2]
[2018-04-23 23:24:12,796] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_float:60 , 是测试点"MyCacl"下的用例"整数加小数",返回的结果res=3.8]
[2018-04-23 23:24:12,799] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_negativeNumber:66 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=-4]
[2018-04-23 23:24:12,802] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_letter:75 , 是测试点"MyCacl"下的用例"整数加字母",返回的结果res=类型错误]
[2018-04-23 23:24:36,354] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:53 , pppppppppppppppp: test_int_int
[2018-04-23 23:24:36,356] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:54 , 是测试点"MyCacl"下的用例"整数加整数",返回的结果res=2]
[2018-04-23 23:24:36,359] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_float:60 , 是测试点"MyCacl"下的用例"整数加小数",返回的结果res=3.8]
[2018-04-23 23:24:36,361] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_negativeNumber:66 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=-4]
[2018-04-23 23:24:36,364] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_letter:75 , 是测试点"MyCacl"下的用例"整数加字母",返回的结果res=类型错误]
[2018-04-23 23:27:12,785] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_all:25 , pppppppppppppppp: test_select_all
[2018-04-23 23:27:13,795] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_all:32 , 是测试点"SelectMock"下的用例"查询所有",返回的结果res=连接错误。]
[2018-04-23 23:27:14,801] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_first:44 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:27:15,809] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_last:56 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:27:16,818] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_notExist:68 , 是测试点"SelectMock"下的用例"查询一个不存在的",返回的结果res=连接错误。]
[2018-04-23 23:27:57,163] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_float:60 , 是测试点"MyCacl"下的用例"整数加小数",返回的结果res=3.8]
[2018-04-23 23:27:57,168] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:54 , 是测试点"MyCacl"下的用例"整数加整数",返回的结果res=2]
[2018-04-23 23:27:57,172] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_letter:75 , 是测试点"MyCacl"下的用例"整数加字母",返回的结果res=类型错误]
[2018-04-23 23:27:57,176] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_negativeNumber:66 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=-4]
[2018-04-23 23:27:58,189] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_all:32 , 是测试点"SelectMock"下的用例"查询所有",返回的结果res=连接错误。]
[2018-04-23 23:27:59,198] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_first:44 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:28:00,207] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_last:56 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:28:01,215] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_notExist:68 , 是测试点"SelectMock"下的用例"查询一个不存在的",返回的结果res=连接错误。]
[2018-04-23 23:28:33,583] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_float:60 , 是测试点"MyCacl"下的用例"整数加小数",返回的结果res=3.8]
[2018-04-23 23:28:33,587] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:54 , 是测试点"MyCacl"下的用例"整数加整数",返回的结果res=2]
[2018-04-23 23:28:33,590] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_letter:75 , 是测试点"MyCacl"下的用例"整数加字母",返回的结果res=类型错误]
[2018-04-23 23:28:33,594] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_negativeNumber:66 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=-4]
[2018-04-23 23:28:34,609] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_all:32 , 是测试点"SelectMock"下的用例"查询所有",返回的结果res=连接错误。]
[2018-04-23 23:28:35,622] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_first:44 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:28:36,632] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_last:56 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:28:37,644] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_notExist:68 , 是测试点"SelectMock"下的用例"查询一个不存在的",返回的结果res=连接错误。]
[2018-04-23 23:28:54,127] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_float:60 , 是测试点"MyCacl"下的用例"整数加小数",返回的结果res=3.8]
[2018-04-23 23:28:54,131] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:53 , 当前方法: test_int_int
[2018-04-23 23:28:54,135] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:54 , 是测试点"MyCacl"下的用例"整数加整数",返回的结果res=2]
[2018-04-23 23:28:54,139] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_letter:75 , 是测试点"MyCacl"下的用例"整数加字母",返回的结果res=类型错误]
[2018-04-23 23:28:54,143] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_negativeNumber:66 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=-4]
[2018-04-23 23:28:54,147] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_all:25 , 当前方法: test_select_all
[2018-04-23 23:28:55,159] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_all:32 , 是测试点"SelectMock"下的用例"查询所有",返回的结果res=连接错误。]
[2018-04-23 23:28:56,167] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_first:44 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:28:57,175] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_last:56 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:28:58,182] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_notExist:68 , 是测试点"SelectMock"下的用例"查询一个不存在的",返回的结果res=连接错误。]
[2018-04-23 23:36:35,730] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"None",返回的结果res=3]
[2018-04-23 23:36:35,735] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"None",返回的结果res=3.5]
[2018-04-23 23:36:35,739] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"None",返回的结果res=类型错误]
[2018-04-23 23:36:35,744] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"None",返回的结果res=类型错误]
[2018-04-23 23:36:35,750] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"None",返回的结果res=4.1]
[2018-04-23 23:36:35,755] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"None",返回的结果res=1]
[2018-04-23 23:36:35,759] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"None",返回的结果res=0.5]
[2018-04-23 23:36:35,765] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"None",返回的结果res=-3]
[2018-04-23 23:36:35,769] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"None",返回的结果res=1]
[2018-04-23 23:36:35,775] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"None",返回的结果res=0.5]
[2018-04-23 23:36:35,780] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"None",返回的结果res=-1]
[2018-04-23 23:36:35,786] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"None",返回的结果res=类型错误]
[2018-04-23 23:38:44,823] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"整数相加",返回的结果res=3]
[2018-04-23 23:38:44,823] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"",返回的结果res=3.5]
[2018-04-23 23:38:44,823] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"",返回的结果res=类型错误]
[2018-04-23 23:38:44,824] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"",返回的结果res=类型错误]
[2018-04-23 23:38:44,825] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"",返回的结果res=4.1]
[2018-04-23 23:38:44,826] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"",返回的结果res=1]
[2018-04-23 23:38:44,826] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"",返回的结果res=0.5]
[2018-04-23 23:38:44,826] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"",返回的结果res=-3]
[2018-04-23 23:38:44,827] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"",返回的结果res=1]
[2018-04-23 23:38:44,827] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"",返回的结果res=0.5]
[2018-04-23 23:38:44,828] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"",返回的结果res=-1]
[2018-04-23 23:38:44,828] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"",返回的结果res=类型错误]
[2018-04-23 23:39:52,511] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"整数相加",返回的结果res=3]
[2018-04-23 23:39:52,511] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"小数加整数",返回的结果res=3.5]
[2018-04-23 23:39:52,512] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"整数加字母",返回的结果res=类型错误]
[2018-04-23 23:39:52,512] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"整数加特殊字符",返回的结果res=类型错误]
[2018-04-23 23:39:52,513] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"小数相加",返回的结果res=4.1]
[2018-04-23 23:39:52,513] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"负数加整数",返回的结果res=1]
[2018-04-23 23:39:52,513] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"负数加小数",返回的结果res=0.5]
[2018-04-23 23:39:52,514] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"负数相加",返回的结果res=-3]
[2018-04-23 23:39:52,514] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"0加整数",返回的结果res=1]
[2018-04-23 23:39:52,514] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"0加小数",返回的结果res=0.5]
[2018-04-23 23:39:52,514] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"0加负数",返回的结果res=-1]
[2018-04-23 23:39:52,515] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl"下的用例"整数加空",返回的结果res=类型错误]
[2018-04-23 23:40:19,488] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"整数相加",返回的结果res=3]
[2018-04-23 23:40:19,488] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"小数加整数",返回的结果res=3.5]
[2018-04-23 23:40:19,489] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"整数加字母",返回的结果res=类型错误]
[2018-04-23 23:40:19,489] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"整数加特殊字符",返回的结果res=类型错误]
[2018-04-23 23:40:19,490] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"小数相加",返回的结果res=4.1]
[2018-04-23 23:40:19,490] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"负数加整数",返回的结果res=1]
[2018-04-23 23:40:19,490] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"负数加小数",返回的结果res=0.5]
[2018-04-23 23:40:19,491] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"负数相加",返回的结果res=-3]
[2018-04-23 23:40:19,491] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"0加整数",返回的结果res=1]
[2018-04-23 23:40:19,491] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"0加小数",返回的结果res=0.5]
[2018-04-23 23:40:19,491] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"0加负数",返回的结果res=-1]
[2018-04-23 23:40:19,491] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"整数加空",返回的结果res=类型错误]
[2018-04-23 23:40:26,463] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_float:60 , 是测试点"MyCacl"下的用例"整数加小数",返回的结果res=3.8]
[2018-04-23 23:40:26,466] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:53 , 当前方法: test_int_int
[2018-04-23 23:40:26,470] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:54 , 是测试点"MyCacl"下的用例"整数加整数",返回的结果res=2]
[2018-04-23 23:40:26,473] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_letter:75 , 是测试点"MyCacl"下的用例"整数加字母",返回的结果res=类型错误]
[2018-04-23 23:40:26,478] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_negativeNumber:66 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=-4]
[2018-04-23 23:40:26,478] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"整数相加",返回的结果res=3]
[2018-04-23 23:40:26,479] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"小数加整数",返回的结果res=3.5]
[2018-04-23 23:40:26,479] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"整数加字母",返回的结果res=类型错误]
[2018-04-23 23:40:26,480] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"整数加特殊字符",返回的结果res=类型错误]
[2018-04-23 23:40:26,480] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"小数相加",返回的结果res=4.1]
[2018-04-23 23:40:26,481] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"负数加整数",返回的结果res=1]
[2018-04-23 23:40:26,481] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"负数加小数",返回的结果res=0.5]
[2018-04-23 23:40:26,481] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"负数相加",返回的结果res=-3]
[2018-04-23 23:40:26,482] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"0加整数",返回的结果res=1]
[2018-04-23 23:40:26,482] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"0加小数",返回的结果res=0.5]
[2018-04-23 23:40:26,482] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"0加负数",返回的结果res=-1]
[2018-04-23 23:40:26,482] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"整数加空",返回的结果res=类型错误]
[2018-04-23 23:40:26,507] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_all:25 , 当前方法: test_select_all
[2018-04-23 23:40:27,519] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_all:32 , 是测试点"SelectMock"下的用例"查询所有",返回的结果res=连接错误。]
[2018-04-23 23:40:28,526] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_first:44 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:40:29,536] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_last:56 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:40:30,549] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_notExist:68 , 是测试点"SelectMock"下的用例"查询一个不存在的",返回的结果res=连接错误。]
[2018-04-23 23:46:58,182] [DEBUG] [G:\my_rf\test_case\testAdd2 - 副本.py : test_cacl:38 , 是测试点"MyCacl2"下的用例"None",返回的结果res=3]
[2018-04-23 23:46:58,187] [DEBUG] [G:\my_rf\test_case\testAdd2 - 副本.py : test_cacl:38 , 是测试点"MyCacl2"下的用例"None",返回的结果res=3.5]
[2018-04-23 23:46:58,193] [DEBUG] [G:\my_rf\test_case\testAdd2 - 副本.py : test_cacl:38 , 是测试点"MyCacl2"下的用例"None",返回的结果res=4.1]
[2018-04-23 23:47:34,908] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_float:60 , 是测试点"MyCacl"下的用例"整数加小数",返回的结果res=3.8]
[2018-04-23 23:47:34,912] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:53 , 当前方法: test_int_int
[2018-04-23 23:47:34,915] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_int:54 , 是测试点"MyCacl"下的用例"整数加整数",返回的结果res=2]
[2018-04-23 23:47:34,919] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_letter:75 , 是测试点"MyCacl"下的用例"整数加字母",返回的结果res=类型错误]
[2018-04-23 23:47:34,924] [DEBUG] [G:\my_rf\test_case\testAdd.py : test_int_negativeNumber:66 , 是测试点"MyCacl"下的用例"整数加负数",返回的结果res=-4]
[2018-04-23 23:47:34,924] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"整数相加",返回的结果res=3]
[2018-04-23 23:47:34,924] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"小数加整数",返回的结果res=3.5]
[2018-04-23 23:47:34,925] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"整数加字母",返回的结果res=类型错误]
[2018-04-23 23:47:34,925] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"整数加特殊字符",返回的结果res=类型错误]
[2018-04-23 23:47:34,926] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"小数相加",返回的结果res=4.1]
[2018-04-23 23:47:34,926] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"负数加整数",返回的结果res=1]
[2018-04-23 23:47:34,926] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"负数加小数",返回的结果res=0.5]
[2018-04-23 23:47:34,927] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"负数相加",返回的结果res=-3]
[2018-04-23 23:47:34,927] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"0加整数",返回的结果res=1]
[2018-04-23 23:47:34,927] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"0加小数",返回的结果res=0.5]
[2018-04-23 23:47:34,927] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"0加负数",返回的结果res=-1]
[2018-04-23 23:47:34,928] [DEBUG] [G:\my_rf\test_case\testAdd2.py : test_cacl:46 , 是测试点"MyCacl2"下的用例"整数加空",返回的结果res=类型错误]
[2018-04-23 23:47:34,951] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_all:25 , 当前方法: test_select_all
[2018-04-23 23:47:35,963] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_all:32 , 是测试点"SelectMock"下的用例"查询所有",返回的结果res=连接错误。]
[2018-04-23 23:47:36,970] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_first:44 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:47:37,978] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_exist_last:56 , 是测试点"SelectMock"下的用例"查询一个存在的",返回的结果res=连接错误。]
[2018-04-23 23:47:38,984] [DEBUG] [G:\my_rf\test_case\testSelect.py : test_select_one_notExist:68 , 是测试点"SelectMock"下的用例"查询一个不存在的",返回的结果res=连接错误。]
[2018-04-25 11:28:59,795] [DEBUG] [F:/my_rf/core/logger.py : <module>:42 , http://www.cnblogs.com/UncleYong/
[2018-04-25 11:29:08,486] [DEBUG] [F:/my_rf/core/logger.py : <module>:42 , http://www.cnblogs.com/UncleYong/
[2018-04-25 11:30:16,159] [DEBUG] [F:/my_rf/core/logger.py : <module>:42 , http://www.cnblogs.com/UncleYong/
